apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-mtu-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - name: mtu-migration.service
          enabled: true
          contents: |
            [Unit]
            Description=Configures interfaces and routes with temporary MTUs during MTU migration
            Requires=openvswitch.service ovs-configuration.service
            Wants=NetworkManager-wait-online.service
            After=NetworkManager-wait-online.service openvswitch.service network.service ovs-configuration.service
            Before=kubelet-dependencies.target node-valid-hostname.service
            
            [Service]
            # Need oneshot to delay kubelet
            Type=oneshot
            Environment=NETWORK_TYPE=OVNKubernetes
            Environment=TARGET_MTU=9000
            Environment=CNI_TARGET_MTU=8800
            ExecStart=/usr/local/bin/mtu-migration.sh
            StandardOutput=journal+console
            StandardError=journal+console
            
            [Install]
            WantedBy=kubelet-dependencies.target
    storage:
      files:
        - path: /etc/NetworkManager/conf.d/99-enp1s0-mtu.conf
          mode: 0644
          overwrite: false
          contents:
            source: data:text/plain;charset=utf-8;base64,W2Nvbm5lY3Rpb24tZW5wMXMwLW10dV0KbWF0Y2gtZGV2aWNlPWludGVyZmFjZS1uYW1lOmVucDFzMApldGhlcm5ldC5tdHU9OTAwMAo=
        - path: /etc/NetworkManager/conf.d/99-enp1s0-mtu.conf
          mode: 0644
          overwrite: false
          contents:
            source: data:text/plain;charset=utf-8;base64,

---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-mtu-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - name: mtu-migration.service
          enabled: true
          contents: |
            [Unit]
            Description=Configures interfaces and routes with temporary MTUs during MTU migration
            Requires=openvswitch.service ovs-configuration.service
            Wants=NetworkManager-wait-online.service
            After=NetworkManager-wait-online.service openvswitch.service network.service ovs-configuration.service
            Before=kubelet-dependencies.target node-valid-hostname.service
            
            [Service]
            # Need oneshot to delay kubelet
            Type=oneshot
            Environment=NETWORK_TYPE=OVNKubernetes
            Environment=TARGET_MTU=9000
            Environment=CNI_TARGET_MTU=8800
            ExecStart=/usr/local/bin/mtu-migration.sh
            StandardOutput=journal+console
            StandardError=journal+console
            
            [Install]
            WantedBy=kubelet-dependencies.target
    storage:
      files:
        - path: /etc/NetworkManager/conf.d/99-eno12399-mtu.conf
          mode: 0644
          overwrite: false
          contents:
            source: data:text/plain;charset=utf-8;base64,W2Nvbm5lY3Rpb24tZW5vMTIzOTktbXR1XQptYXRjaC1kZXZpY2U9aW50ZXJmYWNlLW5hbWU6ZW5vMTIzOTkKZXRoZXJuZXQubXR1PTkwMDAK