apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  operand:
    image: quay.io/yshnaidm/node-feature-discovery:dpf
  workerEnvs:
    - name: KUBERNETES_SERVICE_HOST
      value: api.CLUSTER_FQDN
    - name: KUBERNETES_SERVICE_PORT
      value: "6443"
  workerConfig:
    configData: |
      sources:
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
            - "device"
            - "class"
