apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dpf-operator-privileged-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:dpu-cplane-tenant1:default
  - system:serviceaccount:dpf-operator-system:default
  - system:serviceaccount:dpf-operator-system:dpf-operator-kamaji-etcd
  - system:serviceaccount:dpf-operator-system:dpf-provisioning-controller-manager
  - system:serviceaccount:dpf-operator-system:dpf-operator-controller-manager
  - system:serviceaccount:dpf-operator-system:dpf-operator-node-feature-discovery-worker
volumes:
  - '*'
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dpf-operator-anyuid-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:dpu-cplane-tenant1:default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret