apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-nmstate-bridge
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCiMgV2FpdCBpbmRlZmluaXRlbHkgZm9yIGFuIGludGVyZmFjZSB0byBnZXQgYW4gSVAgYWRkcmVzcyBhbmQgZGVmYXVsdCByb3V0ZQpXQUlUX0lOVEVSVkFMPTUgICMgQ2hlY2sgaW50ZXJ2YWwgaW4gc2Vjb25kcwpBVFRFTVBUPTEKCmVjaG8gIldhaXRpbmcgZm9yIG5ldHdvcmsgY29uZmlndXJhdGlvbi4uLiIKd2hpbGUgdHJ1ZTsgZG8KICAgICMgQ2hlY2sgaWYgd2UgaGF2ZSBhbiBpbnRlcmZhY2Ugd2l0aCBhIGRlZmF1bHQgcm91dGUKICAgIERFRkFVTFRfSU5URVJGQUNFPSQoaXAgcm91dGUgfCBncmVwIGRlZmF1bHQgfCBhd2sgJ3twcmludCAkNX0nIHwgaGVhZCAtbiAxKQoKICAgIGlmIFsgLW4gIiRERUZBVUxUX0lOVEVSRkFDRSIgXTsgdGhlbgogICAgICAgICMgQ2hlY2sgaWYgdGhhdCBpbnRlcmZhY2UgaGFzIGFuIElQIGFkZHJlc3MKICAgICAgICBJUF9BRERSPSQoaXAgYWRkciBzaG93IGRldiAiJERFRkFVTFRfSU5URVJGQUNFIiB8IGdyZXAgLXcgImluZXQiIHwgYXdrICd7cHJpbnQgJDJ9JykKCiAgICAgICAgaWYgWyAtbiAiJElQX0FERFIiIF07IHRoZW4KICAgICAgICAgICAgZWNobyAiTmV0d29yayBpcyByZWFkeS4gSW50ZXJmYWNlICRERUZBVUxUX0lOVEVSRkFDRSBoYXMgSVAgYWRkcmVzcyAkSVBfQUREUiIKICAgICAgICAgICAgYnJlYWsKICAgICAgICBmaQogICAgZmkKCiAgICBlY2hvICJXYWl0aW5nIGZvciBuZXR3b3JrIGNvbmZpZ3VyYXRpb24uLi4gKEF0dGVtcHQgJEFUVEVNUFQpIgogICAgc2xlZXAgJFdBSVRfSU5URVJWQUwKICAgIEFUVEVNUFQ9JCgoQVRURU1QVCArIDEpKQpkb25lCgojIENoZWNrIGlmIHRoZSBicmlkZ2UgYWxyZWFkeSBleGlzdHMKaWYgaXAgbGluayBzaG93IGJyLWRwdSAmPi9kZXYvbnVsbDsgdGhlbgogICAgZWNobyAiQnJpZGdlIGJyLWRwdSBhbHJlYWR5IGV4aXN0cy4gTm8gbmVlZCB0byBjb25maWd1cmUgaXQuIgogICAgZXhpdCAwCmZpCgojIEZpbmQgdGhlIGludGVyZmFjZSB0aGF0IGhhcyB0aGUgZGVmYXVsdCByb3V0ZQpERUZBVUxUX0lOVEVSRkFDRT0kKGlwIHJvdXRlIHwgZ3JlcCBkZWZhdWx0IHwgYXdrICd7cHJpbnQgJDV9JyB8IGhlYWQgLW4gMSkKCmlmIFsgLXogIiRERUZBVUxUX0lOVEVSRkFDRSIgXTsgdGhlbgogICAgZWNobyAiRXJyb3I6IENvdWxkIG5vdCBmaW5kIGludGVyZmFjZSB3aXRoIGRlZmF1bHQgcm91dGUiID4mMgogICAgZXhpdCAxCmZpCgplY2hvICJGb3VuZCBkZWZhdWx0IGludGVyZmFjZTogJERFRkFVTFRfSU5URVJGQUNFIgoKIyBDcmVhdGUgYSB0ZW1wb3JhcnkgWUFNTCBmaWxlIHdpdGggdGhlIGludGVyZmFjZSBzdWJzdGl0dXRlZApUTVBfRklMRT0kKG1rdGVtcCkKCmNhdCA+ICIkVE1QX0ZJTEUiIDw8IEVPRgppbnRlcmZhY2VzOgogIC0gbmFtZTogYnItZHB1CiAgICB0eXBlOiBsaW51eC1icmlkZ2UKICAgIHN0YXRlOiB1cAogICAgaXB2NjoKICAgICAgZW5hYmxlZDogZmFsc2UKICAgIGlwdjQ6CiAgICAgIGVuYWJsZWQ6IHRydWUKICAgICAgZGhjcDogdHJ1ZQogICAgICBhdXRvLWRuczogdHJ1ZQogICAgICBhdXRvLWdhdGV3YXk6IHRydWUKICAgICAgYXV0by1yb3V0ZXM6IHRydWUKICAgIGJyaWRnZToKICAgICAgb3B0aW9uczoKICAgICAgICBzdHA6CiAgICAgICAgICBlbmFibGVkOiBmYWxzZQogICAgICBwb3J0OgogICAgICAgIC0gbmFtZTogJERFRkFVTFRfSU5URVJGQUNFCkVPRgoKZWNobyAiQ3JlYXRlZCBOTVN0YXRlIGNvbmZpZ3VyYXRpb24gd2l0aCBpbnRlcmZhY2UgJERFRkFVTFRfSU5URVJGQUNFIgplY2hvICJBcHBseWluZyBjb25maWd1cmF0aW9uIHVzaW5nIG5tc3RhdGVjdGwuLi4iCgojIEFwcGx5IHRoZSBjb25maWd1cmF0aW9uCm5tc3RhdGVjdGwgYXBwbHkgIiRUTVBfRklMRSIKUkVTVUxUPSQ/CgojIENsZWFuIHVwCnJtICIkVE1QX0ZJTEUiCgojIFJldHVybiB0aGUgcmVzdWx0CmV4aXQgJFJFU1VMVAo=
          mode: 0755
          overwrite: true
          path: /usr/local/bin/apply-nmstate-bridge.sh
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Apply NMState bridge configuration
            After=network.target NetworkManager.service
            Wants=NetworkManager.service
            
            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/apply-nmstate-bridge.sh
            RemainAfterExit=yes
            
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: nmstate-bridge.service
