apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  externalIP:
    policy: {}
  networkType: NVIDIA-OVN
  serviceNetwork:
    - 172.30.0.0/16
  disableMultiNetwork: false
  deployKubeProxy: false
