---
# ngc-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ngc-doca-https-helm
  namespace: dpf-operator-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nvstaging-doca-https
  url: https://helm.ngc.nvidia.com/nvstaging/doca
  type: helm
  username: ${no_variable}oauthtoken
  password: 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
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-doca-oci-helm
  namespace: dpf-operator-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nvstaging-doca-oci
  url: nvcr.io/nvstaging/doca
  type: helm
  username: ${no_variable}oauthtoken
  password: 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
